In [69]:
import numpy as np

In [70]:
# https://jakevdp.github.io/PythonDataScienceHandbook/02.05-computation-on-arrays-broadcasting.html

In [71]:
a = np.array([1, 2, 3])

In [72]:
a + 5

array([6, 7, 8])

In [73]:
b = np.ones((3,3))

In [74]:
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [75]:
a + b

array([[2., 3., 4.],
       [2., 3., 4.],
       [2., 3., 4.]])

In [76]:
# Broadcasting changes the smaller vector or array and boosts it

In [77]:
a = np.arange(3)
b = np.ones(3)[:, np.newaxis]

In [78]:
a

array([0, 1, 2])

In [79]:
b

array([[1.],
       [1.],
       [1.]])

In [80]:
a + b

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [81]:
b = np.arange(3)

In [82]:
a

array([0, 1, 2])

In [83]:
b

array([0, 1, 2])

In [84]:
a + b

array([0, 2, 4])

In [85]:
a = np.arange(3).reshape(3,1)
b = np.arange(3)
a+b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [86]:
a = np.ones((3, 2))
# b = np.arange(12).reshape(-1, 2)
# a+b
a

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [87]:
a = np.ones((3, 2))
b = np.arange(3)

In [88]:
b[:, np.newaxis]

array([[0],
       [1],
       [2]])

In [89]:
a+b[:, np.newaxis]

array([[1., 1.],
       [2., 2.],
       [3., 3.]])

In [98]:
x = np.random.random((5,3))
x_m = x.mean(0)
x_m

array([0.5427221 , 0.53229009, 0.29727553])

In [99]:
(x - x_m).mean(0)

array([ 6.66133815e-17, -8.88178420e-17, -2.22044605e-17])

In [100]:
x = np.linspace(0, 5, 50)

In [102]:
y = np.linspace(0,5,50)[:, np.newaxis]

In [104]:
z = np.sin(x) + np.cos(x)

In [106]:
z


array([ 1.        ,  1.09666218,  1.18191546,  1.25487292,  1.31477556,
        1.36100021,  1.39306597,  1.41063924,  1.41353722,  1.40172976,
        1.37533968,  1.33464153,  1.28005872,  1.21215907,  1.13164897,
        1.039366  ,  0.93627019,  0.82343408,  0.70203155,  0.57332557,
        0.43865511,  0.2994212 ,  0.15707232,  0.01308937, -0.13102975,
       -0.27378573, -0.41369344, -0.54929737, -0.6791868 , -0.80201045,
       -0.91649054, -1.02143611, -1.11575538, -1.19846712, -1.26871084,
       -1.32575579, -1.36900851, -1.39801903, -1.41248554, -1.41225754,
       -1.39733741, -1.36788037, -1.32419286, -1.26672938, -1.19608774,
       -1.11300284, -1.01833904, -0.91308116, -0.79832423, -0.67526209])